server:
    port: 8080
    contextPath: /
spring:
    rest:
        page-size: 10
---
spring:
    profiles: local,default
    datasource:
        url: jdbc:h2:~/test
        username: SA
        password:
        driverClassName: org.h2.Driver
        defaultSchema:
        maxPoolSize: 10
        hibernate:
            hbm2ddl.method: create-drop
            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2
---
spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://localhost:3306/test?useSSL=false
        username: root
        password: 12345
        driverClassName: com.mysql.jdbc.Driver
        defaultSchema:
        maxPoolSize: 20
        hibernate:
            hbm2ddl.method: update
            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.MySQLDialect
